linters
mirumon/mirumon-telegram-bot pull request #1
Opened 2019-10-13 17:56 UTC by Opti213

2019-10-13 18:11 UTC, nsidnev requested changes

2019-10-13 18:11 UTC, nsidnev commented on app/main.py
> +def help_message(message: Message) -> Any:
аннотация неправильная

2019-10-13 18:11 UTC, nsidnev commented on app/main.py
>  def send_message(message: Message) -> Any:
тут тоже аннотацию надо другую

2019-10-13 18:11 UTC, nsidnev commented on app/main.py
> +    logger.debug(message.text)
тут нужно более информативное сообщение к логам

2019-10-13 18:11 UTC, nsidnev commented on app/main.py
> +        resp = requests.get("http://api.icndb.com/jokes/random")
урл должен быть захардкожен в константе тогда, а не в коде

2019-10-13 18:11 UTC, nsidnev commented on pyproject.toml
>  description = ""
добавь описание

2019-10-13 18:11 UTC, nsidnev commented on pyproject.toml
>  name = "telegram-bot"
имя должно быть `mirumon-tg-bot`

2019-10-13 18:15 UTC, Opti213 commented on app/main.py
> +def help_message(message: Message) -> Any:
В каком месте?

2019-10-13 18:16 UTC, Opti213 commented on app/main.py
> +    logger.debug(message.text)
Ты просто хочешь докопаться, да?

2019-10-13 18:16 UTC, nsidnev commented on app/main.py
> +def help_message(message: Message) -> Any:
в возврате

2019-10-13 18:20 UTC, Opti213 commented on pyproject.toml
>  description = ""
Что в нем писать?

2019-10-13 18:20 UTC, Opti213 commented on app/main.py
> +def help_message(message: Message) -> Any:
...

2019-10-13 18:21 UTC, nsidnev commented on pyproject.toml
>  description = ""
Telegram bot for mirumon monitoring service

2019-10-13 18:21 UTC, Opti213 commented on app/main.py
> +def help_message(message: Message) -> Any:
Там так-то Optional[Message], на который плевать

2019-10-13 18:22 UTC, nsidnev commented on app/main.py
> +def help_message(message: Message) -> Any:
у тебя из хандлера ничего не возвращается. там `None` а не `Any`

2019-10-13 18:25 UTC, Opti213 commented on app/main.py
> +def help_message(message: Message) -> Any:
Тут на возвращаемый тип вообще пофиг, я с тем же успехом могу возвращать Message

2019-10-13 20:40 UTC, nsidnev requested changes

2019-10-13 20:40 UTC, nsidnev commented on app/main.py
> +from app.resurses.const.strings import JOKE
```suggestion
from app.resources.const.strings import JOKE
```

2019-10-13 20:40 UTC, nsidnev commented on app/main.py
> +from app.resurses.messages.common import HELLO, HELP
```suggestion
from app.resources.messages.common import HELLO, HELP
```

2019-10-13 20:43 UTC, nsidnev approved these changes

2019-10-13 20:44 UTC, merged

2019-10-14 12:04 UTC, Opti213 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Добавить линтеры](https://trello.com/c/fn9q4CWu/48-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%BB%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D1%8B)