Feature/commands
mirumon/mirumon-telegram-bot pull request #3
Opened 2019-10-15 07:38 UTC by Opti213

2019-10-15 09:25 UTC, Opti213 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Добавить команду просмотра устройств](https://trello.com/c/cjUpclpW/55-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D1%83-%D0%BF%D1%80%D0%BE%D1%81%D0%BC%D0%BE%D1%82%D1%80%D0%B0-%D1%83%D1%81%D1%82%D1%80%D0%BE%D0%B9%D1%81%D1%82%D0%B2)

2019-10-15 16:11 UTC, nkhitrov requested changes

2019-10-15 16:11 UTC, nkhitrov commented on app/main.py
> +                         )
отправлять отдельное сообщение на каждый комп не оч удобно, много нотификашек и читать неудобно. лучше сортировать заранее по доменам и потом уже одним сообщением отправлять

2019-10-15 16:11 UTC, nkhitrov commented on app/main.py
> +    computers = [Computer(**computer) for computer in resp.json()]
это стоит вынести в отдельную функцию сразу. и возможно стоит добавить отправку какого-то сообщения пользователю, что произошла ошибка. все таки с телегой иногда бывают сбои, будет трудно отличить ошибку сервера от проблем с подключением к телеге.

2019-10-15 16:11 UTC, Slyfoxy commented on app/main.py
>  def send_message(message: Message) -> None:
этот обработчик вообще нужен, если он только логирует? без него не работает?

2019-10-15 16:11 UTC, Slyfoxy commented on app/schemas/response_models.py
> +    event: EventComputeDetails
эти классы нигде не используются и они не нужны для использования rest api

2019-10-15 16:11 UTC, Slyfoxy commented on app/main.py
> +    resp = requests.get(API_BASE_URL + "/computers")
`computers` можно закинуть в enum, чтобы не хардкодить. да и ивентов много, все равно потом придется создавать

2019-10-16 15:55 UTC, Opti213 commented on app/main.py
>  def send_message(message: Message) -> None:
Это тупо эхо

2019-10-16 15:56 UTC, Opti213 commented on app/main.py
> +    computers = [Computer(**computer) for computer in resp.json()]
Куда, как и зачем?
Ты хочешь отделльную функцию, которая будет, в зависимости от ошибки ответа, что-то писать юзеру?

2019-10-16 16:01 UTC, Slyfoxy commented on app/main.py
>  def send_message(message: Message) -> None:
зачем? оно не нужно

2019-10-16 16:06 UTC, nkhitrov commented on app/main.py
> +    computers = [Computer(**computer) for computer in resp.json()]
где ты видишь, чтобы я выделил у тебя строки кода, которые что-то пишут юзеру? отправка сообщений только во вьюхе. я говорю о функции, которая в себе инкапсулирует запрос. аля `get_computers`, которая возвращает список компов, либо вызывает исключение. ты его ловишь во вьюхе и пишешь юзеру, что ошибка сервера и т.п. Или выводить ошибку сервера

2019-10-16 18:01 UTC, nkhitrov requested changes

2019-10-16 18:01 UTC, nkhitrov commented on app/main.py
> +    resp = requests.get(str(API_BASE_URL) + "/computers")
можно привести к строке сразу в конфиге

2019-10-16 18:01 UTC, Slyfoxy commented on app/main.py
> +typing.cast(str, SECRET_TOKEN)
лишнее. приводи к строке сразу в конфиге

2019-10-16 18:08 UTC, Opti213 commented on app/main.py
> +    resp = requests.get(str(API_BASE_URL) + "/computers")
Афигеть! Полезное замечание!!!!!!!! Спасибо)

2019-10-16 18:19 UTC, nkhitrov approved these changes

2019-10-16 18:28 UTC, nsidnev submitted a review, later dismissed

2019-10-16 18:29 UTC, Opti213 commented on app/main.py
> +    computers = [Computer(**computer) for computer in resp.json()]
Чекай

2019-10-16 18:29 UTC, Opti213 commented on app/main.py
>  def send_message(message: Message) -> None:
Убрал еще два коммита назад

2019-10-16 18:42 UTC, nsidnev commented on app/config.py
> +SECRET_TOKEN = str(os.getenv("SECRET_TOKEN"))
тк для этого бота не понадобится starlette с конфигом, то тут надо юзать конфиг из https://5d5d36c5b8219300085d081b--pydantic-docs.netlify.com/#id5

2019-10-16 18:46 UTC, nsidnev requested changes

2019-10-16 18:46 UTC, nsidnev commented on app/main.py
> +        msg += f"{computer.name} [{computer.username}]\n"
билдить сообщение руками это плохо, надо заюзать шаблонизатор

2019-10-16 18:46 UTC, nsidnev commented on app/main.py
> +def joke(message: Message) -> None:
это тут теперь зачем?

2019-10-17 17:21 UTC, nsidnev approved these changes

2019-10-17 17:21 UTC, merged