Feature/command software
mirumon/mirumon-telegram-bot pull request #5
Opened 2019-10-29 14:25 UTC by Opti213

2019-10-30 10:00 UTC, Opti213 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Добавить тесты на команду /computers](https://trello.com/c/RLI1VgVq/65-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D1%82%D0%B5%D1%81%D1%82%D1%8B-%D0%BD%D0%B0-%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D1%83-computers)

2019-10-30 19:02 UTC, Opti213 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Добавить команду просмотра установленного ПО на устройстве](https://trello.com/c/KqSe8J3z/85-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D1%83-%D0%BF%D1%80%D0%BE%D1%81%D0%BC%D0%BE%D1%82%D1%80%D0%B0-%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BF%D0%BE-%D0%BD%D0%B0-%D1%83%D1%81%D1%82%D1%80%D0%BE%D0%B9%D1%81%D1%82%D0%B2%D0%B5)

2019-10-30 19:04 UTC, Aredruss approved these changes
looks ok

2019-10-30 19:15 UTC, nkhitrov approved these changes

2019-10-30 19:15 UTC, nkhitrov commented on app/config.py
> +    api_base_url: str
можно использовать специальный тип для урлов

2019-10-30 19:15 UTC, nkhitrov commented on .gitignore
> +test.py
стоит убрать `my` и `test.py` заменить на `tmp.*`, как вариант

2019-10-30 19:15 UTC, Slyfoxy commented on app/main.py
> +    msg = INFO_TEMPLATE.render(computers=computers)
использование не через `messages.`

2019-10-30 19:15 UTC, Slyfoxy commented on app/main.py
> +    mac_address = get_args(message)[0]
тут надо бы проверку на наличие аргументов добавить и в идеале выводить хелпу, что надо ввести аргумент

2019-10-30 19:15 UTC, Slyfoxy commented on app/resources/messages/__init__.py
> +JOKE = "joke"
почему Вики? это же мирумон бот, пускай и говорит, что он мирумон.
в хелпе должна быть инфы по командам и не должно быть `joke`. ты хандлер удалил, а это, видимо, изменить забыл

2019-10-30 19:15 UTC, Slyfoxy commented on app/resources/messages/__init__.py
> +)
должен быть не шаблон, а в файл. и если делаешь шаблоны, то не делай отступы такие, они будут и в тексте

2019-10-30 19:15 UTC, Slyfoxy commented on app/resources/messages/__init__.py
> +    """
лишние отступы слева

2019-10-30 19:15 UTC, Slyfoxy commented on app/services/requests.py
> +        config.api_base_url + f"/computers/{mac_adres}/installed-programs"
можно заменить одной f строкой

2019-10-30 19:15 UTC, Slyfoxy commented on app/services/requests.py
> +        return []
может лучше сообщать пользователю, что сервер не отвечает? так он может подумать, что что-то случилось с компами

2019-10-30 19:16 UTC, nkhitrov requested changes
Осталось мини легаси, команда сделана не по тз и без валидации данных на кол-во (и вход, и выход)

2019-10-31 22:01 UTC, nsidnev requested changes

2019-10-31 22:01 UTC, nsidnev commented on .gitignore
> +.env
это уже есть в файле

2019-10-31 22:01 UTC, nsidnev commented on app/config.py
> +    api_base_url: URL
у pydantic свои URL парсеры https://pydantic-docs.helpmanual.io/usage/types/#urls

2019-10-31 22:01 UTC, nsidnev commented on app/main.py
> +        bot.reply_to(message, f"bad response ({e.status_code})")
не шаблон. а для юзера еще и непонятное сообщение
```
> /computers
< bad response 503
> WTF?!
```

2019-10-31 22:01 UTC, nsidnev commented on app/main.py
> +    logger.info(computers)
лог без сообщения что конкретно логируется

2019-10-31 22:01 UTC, nsidnev commented on app/main.py
> +        bot.reply_to(message, "wrong arguments")
не сказано, какой формат и какие аргументы нужны

2019-10-31 22:01 UTC, nsidnev commented on app/main.py
> +        bot.reply_to(message, f"bad response ({e.status_code})")
см выше про непонятное сообщение

2019-10-31 22:01 UTC, nsidnev commented on app/main.py
> +        bot.reply_to(message, "no one")
не сообщение из ресурсов

2019-10-31 22:01 UTC, nsidnev commented on app/resources/messages/__init__.py
> +_TEMPLATE_LOOKUP = TemplateLookup(
это должно быть определено перед определением шаблонов и строк

2019-10-31 22:01 UTC, nsidnev commented on app/services/requests.py
> +from httpx.status_codes import StatusCode
nit: можно импортировать напрямую из `httpx`

2019-10-31 22:01 UTC, nsidnev commented on programs.csv
> +7-Zip 19.00 (x64),Igor Pavlov,19.00
этого файла здесь быть не должно

2019-10-31 22:01 UTC, nsidnev commented on setup.cfg
> +    WPS412,
это контролируется настройкой `i-control-code`
https://wemake-python-stylegui.de/en/latest/pages/usage/violations/best_practices.html#wemake_python_styleguide.violations.best_practices.InitModuleHasLogicViolation

2019-10-31 22:01 UTC, nsidnev commented on setup.cfg
> +    WPS421,
это нельзя отключать

2019-10-31 22:01 UTC, nsidnev commented on setup.cfg
> +    WPS431,
это можно контролировать настройкой `nested-classes-whitelist`
https://wemake-python-stylegui.de/en/latest/pages/usage/violations/best_practices.html#wemake_python_styleguide.violations.best_practices.NestedClassViolation

2019-10-31 22:01 UTC, nsidnev commented on setup.cfg
> +    WPS221,
это нельзя отключать

2019-10-31 22:01 UTC, nsidnev commented on setup.cfg
> +    WPS342,
это нельзя отключать

2019-10-31 22:01 UTC, nsidnev commented on app/resources/messages/__init__.py
> +HELP = "\n".join(
почему это не шаблон?

2019-10-31 22:01 UTC, nsidnev commented on app/resources/messages/__init__.py
> +JOKE = "joke"
зачем это теперь?

2019-10-31 22:01 UTC, nsidnev commented on app/resources/messages/__init__.py
> +HELLO = f"Hello, i'm mirumon bot.\n {HELP}"
после выноса хелпы в отдельный шаблон тут можно будет просто включить его в данный

2019-11-04 13:10 UTC, nkhitrov submitted a review, later dismissed

2019-11-04 13:10 UTC, nkhitrov commented on .gitignore
> -.env
все еще не убрал "my" и зачем-то убрал `.env`

2019-11-04 13:10 UTC, nkhitrov commented on app/main.py
> +    bot.send_message(message.chat.id, messages.HELP.render())
если это шаблон, то стоит добавить это в название переменной. но вообще непонятно, зачем делать пустой шаблон без аргументов

2019-11-04 13:10 UTC, nkhitrov commented on app/main.py
> +    logger.debug(f"computers: {computers}")
может лучше вынести такое логирование в саму функцию, которая возвращает данные? так логика команд будет чище и не придется в случае чего каждый раз логи делать при вызове

2019-11-04 13:10 UTC, Slyfoxy commented on app/main.py
> +        bot.reply_to(message, "wrong arguments, please enter /software {mac_address}")
сообщение должно быть в ресурсах

2019-11-04 13:10 UTC, Slyfoxy commented on app/main.py
> +        bot.reply_to(message, f"bad response ({exc.status_code})")
сообщение должно быть в ресурсах

2019-11-04 13:10 UTC, Slyfoxy commented on app/main.py
> +    logger.debug(f"soft {len(software)}, first : {software[0]}")
как и в предыдущем случае, мне кажется, логер стоит переместить в саму функцию

2019-11-04 13:10 UTC, Slyfoxy commented on app/resources/messages/__init__.py
> +HELP = _TEMPLATE_LOOKUP.get_template("hello.txt")
почему переменная называется `help`, а файл `hello`?

2019-11-04 13:10 UTC, Slyfoxy commented on app/services/utility.py
> +    raise ValueError
nit: по идее можно сократить до

```python
_, *args = message.text.split()
return args
```

2019-11-04 13:10 UTC, Slyfoxy commented on app/services/utility.py
> +    msg = "\n".join([f"{soft.name},{soft.vendor},{soft.version}" for soft in software])
вообще по хорошему все таки стоит это в шаблоны переместить, чтобы было проще потом менять и настраивать разные форматы

2019-11-04 13:14 UTC, nkhitrov requested changes
Часть сообщений не вынесена в ресурсы

2019-11-04 13:16 UTC, Slyfoxy commented on app/resources/messages/__init__.py
> +HELP = _TEMPLATE_LOOKUP.get_template("hello.txt")
а где сам файл `hello.txt`?

2019-11-04 13:16 UTC, Slyfoxy commented on app/resources/messages/__init__.py
> +JOKE = "joke"
прописан шаблон на файл, но самого файла нет

2019-11-04 13:18 UTC, nsidnev requested changes

2019-11-04 13:18 UTC, nsidnev commented on app/main.py
> +        bot.reply_to(message, "wrong arguments, please enter /software {mac_address}")
не из ресурсов

2019-11-04 13:18 UTC, nsidnev commented on app/main.py
> +        bot.reply_to(message, f"the service is not responding")
не из ресурсов и тут не нужна f-строка

2019-11-04 13:18 UTC, nsidnev commented on app/resources/messages/__init__.py
> +INFO_TEMPLATE = _TEMPLATE_LOOKUP.get_template("./computers.txt")
здесь не нужен путь относительно текущей директории

2019-11-04 13:18 UTC, nsidnev commented on app/main.py
> +        bot.send_document(message.chat.id, sending_csv_file)
это что и зачем? 
1) почему сначала берется `io.StringIO`, а потом **текст** из него читается и по нему пытаются открыть в бинарном режиме какой-то другой файл(который скорее всего не существует)
2) зачем вообще открывать в бинарном режиме файл?
3) почему нельзя из `get_string_io_with_software` верунть объект, который можно будет спокойно отправить ботов? (telebot использует под капотом requests, поэтому здесь вполне прокатило бы просто поставить поле `name` у `io.StringIO`

2019-11-04 13:18 UTC, nsidnev commented on app/services/requests.py
> +    def __init__(self, status_code: int):
нет аннотации у возврата

2019-11-04 13:18 UTC, nsidnev commented on app/services/requests.py
> +    is_client_error = StatusCode.is_client_error(resp.status_code)
вот это повторяется уже несколько раз, надо вынести

2019-11-04 13:18 UTC, nsidnev commented on app/services/requests.py
> +        logger.error(resp.status_code)
не понятно что за ошибка, бесполезный лог

2019-11-04 13:18 UTC, nsidnev commented on app/services/requests.py
> +    computers.sort(key=lambda cmp: cmp.domain)
почему не отсоритровал сразу через `sorted`?

2019-11-04 13:18 UTC, nsidnev commented on app/services/requests.py
> +    resp = httpx.get(f"{config.api_base_url}/computers")
почему здесь использует хелпер, а не созданный клиент с переданным базовым урлом?

2019-11-04 13:18 UTC, nsidnev commented on app/services/requests.py
> +    resp = httpx.get(f"{config.api_base_url}/computers/{mac_adres}/installed-programs")
см выше про хелпер

2019-11-04 13:18 UTC, nsidnev commented on app/services/requests.py
> +    is_client_error = StatusCode.is_client_error(resp.status_code)
см выше про повтор данного куска кода

2019-11-04 13:18 UTC, nsidnev commented on app/services/requests.py
> +        logger.error(resp.status_code)
см выше про непонятный лог

2019-11-04 13:18 UTC, nsidnev commented on app/services/utility.py
> +def get_string_io_with_software(software: List[Software]) -> io.StringIO:
название раскрывает слишком многое, уместнее было бы `get_software_as_csv_file`

2019-11-04 13:18 UTC, nsidnev commented on app/services/requests.py
> +    computers.sort(key=lambda cmp: cmp.domain)
А еще `WPS` запрещает лямбды и вложенные функции, если это не декораторы и фабрики. Нужно убрать и заменить отдельной обычной функцией. Либо вынеси ответ с листом моделей в отдельную модель и там напиши метод сортировки в валидаторе

2019-11-04 13:21 UTC, nsidnev commented on app/main.py
> +    bot.send_message(message.chat.id, messages.HELP.render())
это файл, который мако при рендеринге откроет, считает и закроет

2019-11-13 09:44 UTC, nkhitrov requested changes

2019-11-13 09:44 UTC, Slyfoxy commented on app/resources/messages/help.txt
> +\software {mac_address} for get csv file with all software
должны же быть `/`, не?)

2019-11-13 09:44 UTC, Slyfoxy commented on app/services/requests.py
> +    computers.sort(key=lambda cmp: cmp.domain)
запрещать лямбды чет такое, в данном случае это удобнее. я бы лучше игнор поставил здесь или на проект

2019-11-14 08:32 UTC, Opti213 commented on app/main.py
> +    msg = INFO_TEMPLATE.render(computers=computers)
Во-первых, вкусовщина. Суффикс TEMPLATE есть
А во-вторых, да, это я исправлю

2019-11-16 20:16 UTC, Opti213 commented on app/main.py
> +        bot.send_document(message.chat.id, sending_csv_file)
Давай я это переделаю в следующей фиче, на telethon?

2019-11-16 23:42 UTC, nkhitrov requested changes

2019-11-16 23:42 UTC, Slyfoxy commented on app/config.py
> +    FILE_WITH_PROGRAMS_NAME = "programs.xlsx"
alarm, убрать

2019-11-16 23:42 UTC, Slyfoxy commented on app/resources/__init__.py
> +http_client = httpx.Client(base_url=config.api_base_url, timeout=15)
поставь 25, на сервере макс. таймаут 20. и вообще это по идее должно быть не в ресурсах, а в модуле, который будет отвечать за апи

2019-11-17 00:00 UTC, nkhitrov approved these changes

2019-11-17 00:03 UTC, Opti213 commented on app/resources/__init__.py
> +http_client = httpx.Client(base_url=config.api_base_url, timeout=15)
лан, это такое себе, но поставил

2019-11-17 00:08 UTC, nkhitrov requested changes

2019-11-17 00:08 UTC, Slyfoxy commented on app/services/requests.py
> +from typing import List
так модуль называть не стоит. в крайнем случае хотя бы `api`. в принципе можно `mirumon_api` или что-то похожее

2019-11-17 00:14 UTC, nkhitrov approved these changes

2019-11-17 00:37 UTC, nkhitrov approved these changes

2019-11-17 00:38 UTC, Opti213 commented on app/services/requests.py
> +from typing import List
И правда. Спасибо

2019-11-17 00:41 UTC, Slyfoxy commented on app/main.py
> +        bot.reply_to(message, f"bad response ({e.status_code})")
исправит в следующем мерже

2019-11-17 00:45 UTC, merged